azs:
- cloud_properties:
    datacenters:
    - clusters:
      - mgmt:
          resource_pool: null
      name: mgmt
  cpi: dd6e31a9aff66e653df7
  name: mgmt
compilation:
  az: mgmt
  env:
    bosh:
      password: $6$781977a2cf44a4b4$ymk.gkDz.5pp3nQSZsX0pSceGKoZpVjEJWTuY4Xm8.DJdFEeDpqu6ipvG8mO7bOL14ls3HizonOHqGUEss6nb.
  network: mgmt
  reuse_compilation_vms: true
  vm_extensions: []
  vm_type: large.cpu
  workers: 4
disk_types:
- cloud_properties:
    type: thick
  disk_size: 1024
  name: "1024"
- cloud_properties:
    type: thick
  disk_size: 2048
  name: "2048"
- cloud_properties:
    type: thick
  disk_size: 5120
  name: "5120"
- cloud_properties:
    type: thick
  disk_size: 10240
  name: "10240"
- cloud_properties:
    type: thick
  disk_size: 20480
  name: "20480"
- cloud_properties:
    type: thick
  disk_size: 30720
  name: "30720"
- cloud_properties:
    type: thick
  disk_size: 51200
  name: "51200"
- cloud_properties:
    type: thick
  disk_size: 76800
  name: "76800"
- cloud_properties:
    type: thick
  disk_size: 102400
  name: "102400"
- cloud_properties:
    type: thick
  disk_size: 153600
  name: "153600"
- cloud_properties:
    type: thick
  disk_size: 204800
  name: "204800"
- cloud_properties:
    type: thick
  disk_size: 307200
  name: "307200"
- cloud_properties:
    type: thick
  disk_size: 512000
  name: "512000"
- cloud_properties:
    type: thick
  disk_size: 768000
  name: "768000"
- cloud_properties:
    type: thick
  disk_size: 1048576
  name: "1048576"
- cloud_properties:
    type: thick
  disk_size: 2097152
  name: "2097152"
- cloud_properties:
    type: thick
  disk_size: 3145728
  name: "3145728"
- cloud_properties:
    type: thick
  disk_size: 4194304
  name: "4194304"
- cloud_properties:
    type: thick
  disk_size: 6291456
  name: "6291456"
- cloud_properties:
    type: thick
  disk_size: 8388608
  name: "8388608"
- cloud_properties:
    type: thick
  disk_size: 10485760
  name: "10485760"
- cloud_properties:
    type: thick
  disk_size: 12582912
  name: "12582912"
- cloud_properties:
    type: thick
  disk_size: 14680064
  name: "14680064"
- cloud_properties:
    type: thick
  disk_size: 16777216
  name: "16777216"
- cloud_properties:
    type: thick
  disk_size: 20971520
  name: "20971520"
- cloud_properties:
    type: thick
  disk_size: 25165824
  name: "25165824"
- cloud_properties:
    type: thick
  disk_size: 29360128
  name: "29360128"
- cloud_properties:
    type: thick
  disk_size: 33554432
  name: "33554432"
networks:
- name: mgmt
  subnets:
  - azs:
    - mgmt
    cloud_properties:
      name: PCF_Tmgt_172.28.104.X_v432
    dns:
    - 172.30.9.9
    gateway: 172.28.104.1
    range: 172.28.104.0/24
    reserved:
    - 172.28.104.0-172.28.104.150
    - 172.28.104.200-172.28.104.245
    static:
    - 172.28.104.152
  type: manual
vm_extensions:
- cloud_properties: {}
  name: public_ip
- cloud_properties:
    disk: 102400
  name: 100GB_ephemeral_disk
- cloud_properties:
    disk: 409600
  name: 400GB_ephemeral_disk
- cloud_properties:
    disk: 1048576
  name: 1TB_ephemeral_disk
vm_types:
- cloud_properties:
    cpu: 1
    disk: 8192
    ram: 512
  name: nano
- cloud_properties:
    cpu: 1
    disk: 8192
    ram: 1024
  name: micro
- cloud_properties:
    cpu: 2
    disk: 8192
    ram: 1024
  name: micro.ram
- cloud_properties:
    cpu: 1
    disk: 8192
    ram: 2048
  name: small
- cloud_properties:
    cpu: 1
    disk: 16384
    ram: 2048
  name: small.disk
- cloud_properties:
    cpu: 2
    disk: 8192
    ram: 4096
  name: medium
- cloud_properties:
    cpu: 1
    disk: 8192
    ram: 8192
  name: medium.mem
- cloud_properties:
    cpu: 2
    disk: 32768
    ram: 4096
  name: medium.disk
- cloud_properties:
    cpu: 4
    disk: 8192
    ram: 2048
  name: medium.cpu
- cloud_properties:
    cpu: 2
    disk: 16384
    ram: 8192
  name: large
- cloud_properties:
    cpu: 1
    disk: 16384
    ram: 16384
  name: large.mem
- cloud_properties:
    cpu: 2
    disk: 65536
    ram: 8192
  name: large.disk
- cloud_properties:
    cpu: 4
    disk: 16384
    ram: 4096
  name: large.cpu
- cloud_properties:
    cpu: 4
    disk: 32768
    ram: 16384
  name: xlarge
- cloud_properties:
    cpu: 2
    disk: 32768
    ram: 32768
  name: xlarge.mem
- cloud_properties:
    cpu: 4
    disk: 131072
    ram: 16384
  name: xlarge.disk
- cloud_properties:
    cpu: 8
    disk: 32768
    ram: 8192
  name: xlarge.cpu
- cloud_properties:
    cpu: 8
    disk: 65536
    ram: 32768
  name: 2xlarge
- cloud_properties:
    cpu: 4
    disk: 65536
    ram: 65536
  name: 2xlarge.mem
- cloud_properties:
    cpu: 8
    disk: 262144
    ram: 32768
  name: 2xlarge.disk
- cloud_properties:
    cpu: 16
    disk: 65536
    ram: 16384
  name: 2xlarge.cpu
